# Site settings
title: civ
description: daemon
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://civforever.com"

# User settings
username: Daemon
user_description: civ
user_title: Software Developer
email: ho0ostgod@gmail.com
twitter_username: Monster
github_username:  daemoncloud
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
